name: Create Github release on Ansible collection
description: |
  Parse CHANGELOG.rst content for dedicated tag and create corresponding Github 
  release

inputs:
  repository:
    description: The Github repository to create release on
    required: true
  tag:
    description: The tag to create relase from.
    required: true
  token:
    description: The Github token with expected permissions
    required: true

runs:
  using: composite
  steps:
    - name: Install python required libraries
      run: pip install -U pyyaml
      shell: bash

    - name: Ensure tag exists
      run: >
        python ${{ github.action_path }}/ensure_tag.py
        --token "${{ inputs.token }}"
        --tag "${{ inputs.tag }}"
        --repo "${{ inputs.repository }}"
      shell: bash

    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}

    - name: Create Github release
      id: parse_release
      run: >-
        python ${{ github.action_path }}/create_release.py
        --repository ${{ inputs.repository }}
        --tag ${{ inputs.tag }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}