---
name: gh_release

on:
  workflow_dispatch:
    inputs:
      repository:
        description: The Github repository to create release on
        required: true
      tag:
        description: The tag to create relase from.
        required: true
      token:
        description: The Github token with expected permissions
        required: true

jobs:
  migrate:
    runs-on: ubuntu-latest
    name: Create Github release
    steps:
      - name: Create github release
        uses: abikouo/dev-tools/.github/actions/ansible_create_release_from_changelogrst@main
        with:
          repository: ${{ inputs.repository }}
          tag: ${{ inputs.tag }}
          token: ${{ inputs.repository }}